version: "2.1"
services: 
 web:
  build: ./web
  expose:
   - "8080"
  depends_on:
   - db
  command: bash -c "wait-for-connection.sh && catalina.sh run"
 
 db:
  build: ./db
  expose: 
   - "5432"
  volumes:
   - /var/lib/postgresql/data
